/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.pantec;

import java.awt.Color;

/**
 *
 * @author Aluno
 */
public class Graficos extends javax.swing.JFrame {

    /**
     * Creates new form Graficos
     */
        
    
    public Graficos() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pgbMemoria = new javax.swing.JProgressBar();
        btnProcessos = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnModoClaro = new javax.swing.JButton();
        lblCpu = new javax.swing.JLabel();
        lblDisco = new javax.swing.JLabel();
        lblMemoria = new javax.swing.JLabel();
        lblPlacaDeVideo = new javax.swing.JLabel();
        pgbCpu = new javax.swing.JProgressBar();
        pgbDisco = new javax.swing.JProgressBar();
        pgbPlacaDeVideo = new javax.swing.JProgressBar();
        lblUsoDisco = new javax.swing.JLabel();
        lblCapaciMem = new javax.swing.JLabel();
        lblTempPlaca = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lblMaxMem = new javax.swing.JLabel();
        lblMaxCpu = new javax.swing.JLabel();
        lblMediaCpu = new javax.swing.JLabel();
        lblMinCpu = new javax.swing.JLabel();
        lblMaxDisc = new javax.swing.JLabel();
        lblMediaDisc = new javax.swing.JLabel();
        lblMinDisc = new javax.swing.JLabel();
        lblMinPlaca = new javax.swing.JLabel();
        lblMediaPlaca = new javax.swing.JLabel();
        lblMaxPlaca = new javax.swing.JLabel();
        lblMinMem = new javax.swing.JLabel();
        lblMediaMem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 17, 60));

        jPanel1.setBackground(new java.awt.Color(0, 17, 60));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(pgbMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 320, 25));

        btnProcessos.setBackground(new java.awt.Color(204, 204, 204));
        btnProcessos.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnProcessos.setText("PROCESSOS");
        btnProcessos.setBorderPainted(false);
        btnProcessos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessosActionPerformed(evt);
            }
        });
        jPanel1.add(btnProcessos, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 530, 160, 50));

        btnExit.setBackground(new java.awt.Color(204, 204, 204));
        btnExit.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnExit.setText("SAIR");
        btnExit.setBorderPainted(false);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, 160, 50));

        btnModoClaro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/escuro.PNG"))); // NOI18N
        btnModoClaro.setBorderPainted(false);
        btnModoClaro.setContentAreaFilled(false);
        btnModoClaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModoClaroActionPerformed(evt);
            }
        });
        jPanel1.add(btnModoClaro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 40));

        lblCpu.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblCpu.setForeground(new java.awt.Color(255, 255, 255));
        lblCpu.setText("CPU");
        jPanel1.add(lblCpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 50, -1));

        lblDisco.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblDisco.setForeground(new java.awt.Color(255, 255, 255));
        lblDisco.setText("DISCO");
        jPanel1.add(lblDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, -1, -1));

        lblMemoria.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblMemoria.setForeground(new java.awt.Color(255, 255, 255));
        lblMemoria.setText("MEMÓRIA");
        jPanel1.add(lblMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, -1, -1));

        lblPlacaDeVideo.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblPlacaDeVideo.setForeground(new java.awt.Color(255, 255, 255));
        lblPlacaDeVideo.setText("PLACA DE VÍDEO");
        jPanel1.add(lblPlacaDeVideo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, -1, -1));

        pgbCpu.setForeground(new java.awt.Color(0, 204, 0));
        pgbCpu.setToolTipText("");
        jPanel1.add(pgbCpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 320, 25));
        jPanel1.add(pgbDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 320, 25));
        jPanel1.add(pgbPlacaDeVideo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 320, 25));

        lblUsoDisco.setBackground(new java.awt.Color(255, 255, 255));
        lblUsoDisco.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblUsoDisco.setForeground(new java.awt.Color(255, 255, 255));
        lblUsoDisco.setText("Uso: ...%");
        jPanel1.add(lblUsoDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 80, 20));

        lblCapaciMem.setBackground(new java.awt.Color(255, 255, 255));
        lblCapaciMem.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblCapaciMem.setForeground(new java.awt.Color(255, 255, 255));
        lblCapaciMem.setText("Capacidade: ...GB");
        jPanel1.add(lblCapaciMem, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 130, 20));

        lblTempPlaca.setBackground(new java.awt.Color(255, 255, 255));
        lblTempPlaca.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblTempPlaca.setForeground(new java.awt.Color(255, 255, 255));
        lblTempPlaca.setText("Temp: ...°C");
        jPanel1.add(lblTempPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, 80, 20));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Min:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 30, 20));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Uso: ...%");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 80, 20));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Máx:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 40, 20));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Máx:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 40, 20));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Máx:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, 40, 20));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Máx:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 40, 20));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Média:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 50, 20));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Média:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 50, 20));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Média:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, 50, 20));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Média:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 50, 20));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Min:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 30, 20));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Min:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, 30, 20));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Min:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 430, 30, 20));

        lblMaxMem.setBackground(new java.awt.Color(255, 255, 255));
        lblMaxMem.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblMaxMem.setForeground(new java.awt.Color(255, 255, 255));
        lblMaxMem.setText("...");
        jPanel1.add(lblMaxMem, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 50, 20));

        lblMaxCpu.setBackground(new java.awt.Color(255, 255, 255));
        lblMaxCpu.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblMaxCpu.setForeground(new java.awt.Color(255, 255, 255));
        lblMaxCpu.setText("...");
        jPanel1.add(lblMaxCpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 50, 20));

        lblMediaCpu.setBackground(new java.awt.Color(255, 255, 255));
        lblMediaCpu.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblMediaCpu.setForeground(new java.awt.Color(255, 255, 255));
        lblMediaCpu.setText("...");
        jPanel1.add(lblMediaCpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 50, 20));

        lblMinCpu.setBackground(new java.awt.Color(255, 255, 255));
        lblMinCpu.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblMinCpu.setForeground(new java.awt.Color(255, 255, 255));
        lblMinCpu.setText("...");
        jPanel1.add(lblMinCpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 50, 20));

        lblMaxDisc.setBackground(new java.awt.Color(255, 255, 255));
        lblMaxDisc.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblMaxDisc.setForeground(new java.awt.Color(255, 255, 255));
        lblMaxDisc.setText("...");
        jPanel1.add(lblMaxDisc, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 50, 20));

        lblMediaDisc.setBackground(new java.awt.Color(255, 255, 255));
        lblMediaDisc.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblMediaDisc.setForeground(new java.awt.Color(255, 255, 255));
        lblMediaDisc.setText("...");
        jPanel1.add(lblMediaDisc, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 50, 20));

        lblMinDisc.setBackground(new java.awt.Color(255, 255, 255));
        lblMinDisc.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblMinDisc.setForeground(new java.awt.Color(255, 255, 255));
        lblMinDisc.setText("...");
        jPanel1.add(lblMinDisc, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, 50, 20));

        lblMinPlaca.setBackground(new java.awt.Color(255, 255, 255));
        lblMinPlaca.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblMinPlaca.setForeground(new java.awt.Color(255, 255, 255));
        lblMinPlaca.setText("...");
        jPanel1.add(lblMinPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 460, 50, 20));

        lblMediaPlaca.setBackground(new java.awt.Color(255, 255, 255));
        lblMediaPlaca.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblMediaPlaca.setForeground(new java.awt.Color(255, 255, 255));
        lblMediaPlaca.setText("...");
        jPanel1.add(lblMediaPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, 50, 20));

        lblMaxPlaca.setBackground(new java.awt.Color(255, 255, 255));
        lblMaxPlaca.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblMaxPlaca.setForeground(new java.awt.Color(255, 255, 255));
        lblMaxPlaca.setText("...");
        jPanel1.add(lblMaxPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, 50, 20));

        lblMinMem.setBackground(new java.awt.Color(255, 255, 255));
        lblMinMem.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblMinMem.setForeground(new java.awt.Color(255, 255, 255));
        lblMinMem.setText("...");
        jPanel1.add(lblMinMem, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 50, 20));

        lblMediaMem.setBackground(new java.awt.Color(255, 255, 255));
        lblMediaMem.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblMediaMem.setForeground(new java.awt.Color(255, 255, 255));
        lblMediaMem.setText("...");
        jPanel1.add(lblMediaMem, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 50, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcessosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProcessosActionPerformed

    private void btnModoClaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModoClaroActionPerformed
        // TODO add your handling code here:
        jPanel1.setBackground(Color.white);
        jLabel9.setForeground(Color.black);
        jLabel10.setForeground(Color.black);
        jLabel11.setForeground(Color.black);
        jLabel12.setForeground(Color.black);
        jLabel13.setForeground(Color.black);
        jLabel14.setForeground(Color.black);
        jLabel18.setForeground(Color.black);
        jLabel15.setForeground(Color.black);
        jLabel16.setForeground(Color.black);
        jLabel17.setForeground(Color.black);
        jLabel19.setForeground(Color.black);
        jLabel20.setForeground(Color.black);
        jLabel21.setForeground(Color.black);
        lblUsoDisco.setForeground(Color.black);
        lblCapaciMem.setForeground(Color.black);
        lblTempPlaca.setForeground(Color.black);
        lblCpu.setForeground(Color.black);
        lblDisco.setForeground(Color.black);
        lblMemoria.setForeground(Color.black);
        lblPlacaDeVideo.setForeground(Color.black);
        
        Color cor = new Color(0, 128, 128);
        btnExit.setBackground(cor);
        btnProcessos.setBackground(cor);
        
        lblMaxCpu.setForeground(Color.black);
        lblMediaCpu.setForeground(Color.black);
        lblMinCpu.setForeground(Color.black);
        lblMaxDisc.setForeground(Color.black);
        lblMediaDisc.setForeground(Color.black);
        lblMinDisc.setForeground(Color.black);
        lblMaxMem.setForeground(Color.black);
        lblMediaMem.setForeground(Color.black);
        lblMinMem.setForeground(Color.black);
        lblMaxPlaca.setForeground(Color.black);
        lblMediaPlaca.setForeground(Color.black);
        lblMinPlaca.setForeground(Color.black);
        
        btnModoClaro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modoclaro.PNG")));
    }//GEN-LAST:event_btnModoClaroActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Graficos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Graficos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Graficos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Graficos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Graficos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnModoClaro;
    private javax.swing.JButton btnProcessos;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCapaciMem;
    private javax.swing.JLabel lblCpu;
    private javax.swing.JLabel lblDisco;
    private javax.swing.JLabel lblMaxCpu;
    private javax.swing.JLabel lblMaxDisc;
    private javax.swing.JLabel lblMaxMem;
    private javax.swing.JLabel lblMaxPlaca;
    private javax.swing.JLabel lblMediaCpu;
    private javax.swing.JLabel lblMediaDisc;
    private javax.swing.JLabel lblMediaMem;
    private javax.swing.JLabel lblMediaPlaca;
    private javax.swing.JLabel lblMemoria;
    private javax.swing.JLabel lblMinCpu;
    private javax.swing.JLabel lblMinDisc;
    private javax.swing.JLabel lblMinMem;
    private javax.swing.JLabel lblMinPlaca;
    private javax.swing.JLabel lblPlacaDeVideo;
    private javax.swing.JLabel lblTempPlaca;
    private javax.swing.JLabel lblUsoDisco;
    private javax.swing.JProgressBar pgbCpu;
    private javax.swing.JProgressBar pgbDisco;
    private javax.swing.JProgressBar pgbMemoria;
    private javax.swing.JProgressBar pgbPlacaDeVideo;
    // End of variables declaration//GEN-END:variables
}
